server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:antoniotaha/config-server-files
          default-label: main
          search-paths:
            - 'greeting-service*'